### ISSUE TITLE
Repozitorij

### ISSUE THREAD

**Issue by jaanos** [stifler9/ANPP-2015-16#1]
Vidim, da si naredil svoj repozitorij, ki pa vseeno izhaja iz vzorčnega. S tem seveda ni nič narobe, opozoril bi te pa, da se boš moral v primeru, da na vzorčnem repozitoriju kaj dodam, nekoliko bolj potruditi, da potegneš spremembe k sebi (med forki se lahko namreč dela pull requeste, tako bo pa potrebno dodati remote za vzorčni repozitorij, narediti pull ter nato pridružiti dobljeno vejo) - ampak upam, da to ne bo problem, glede na to, da si moral že sam spreminjati remote, da si pushal na ta repozitorij.

Svetoval bi ti le, da zamenjaš ime repozitorija z imenom tvojega projekta (za forke to načeloma ni potrebno, saj se po imenu ve, kam sodijo; tukaj pa imaš zdaj svoj projekt, ki pa si zasluži bolj pomenljivo ime:)). Seveda se bo v tem primeru zamenjala pot do repoztorija, tako da bo potrebno popraviti remote na lokalnih kopijah repozitorija, ali pa ga enostavno še enkrat klonirati.

**Comment by stifler9** [comment]
Uvozil sem podatke La lige 2014/15 v tabelo podatki, nato sem želel podatke prikazati z ggplotom, v datoteko prikaz.r sem najprej dodal katere libraryje moram odpreti nato sem naredil vektor fill_golrazlika kateremu sem dodal vrednost 50, saj so gol razlike tudi negativne in sem želel prikazati graf tako, da se vidi kako naraščajo točke po ekipah in obarvati graf glede na gol razliko. zadnjič mi je prikaz narisal graf, zdaj mi ga pa ne in me zanima kako moram dodati podatke, da mi bo graf prikazalo, poleg tega mi javi error ko poženem markdown(v njem še nimam napisanih poročil, ampak nevem kako jih moram napisati, da mi bo odprlo, ko poženem markdown.

**Comment by jaanos** [comment]
Ne vidim, kje imaš narejen uvoz. Najbolje bo, če program z uvozom postaviš v datoteko `uvoz/uvoz.r` - (vzorčno vsebino lahko pobrišeš) tam lahko potem pripraviš tudi graf (ampak ga še ne izrisuj). Uvoze knjižnic (ukazi `library`) bo najbolje premakniti v datoteko `lib/library.r`, da se ti v poročilo ne bodo izpisovala obvestila ob uvozu.

V poročilu lahko pustiš prva dva bloka kode, ki kličeta zgoraj omenjena programa, preostanek pa pobriši. Seveda dodaj še opis tvoje tematike in uvoženih podatkov. Če si graf že pripravil pri uvozu (ali pa drugje - potem bo treba poklicati še to datoteko), lahko v svojem bloku kode v poročilu (na želenem mestu - tako kot histogram v vzorcu) izrišeš graf (lahko pa ga seveda tudi tam narediš).

**Comment by stifler9** [comment]
podatke sem uvozil tako da sem iz spletne strani prekopiral podatke in jih shranil v tabelo kot csv, zdaj sem uredil še uvoz, da mi tabelo uredi in doda stolpce. v datoteki Prikaz.R sem želel napisati ukaze, da mi izpiše funkcijo kako točke naraščajo po ekipah in želel sem tudi dodati barve glede na gol razliko, vendar mi ne izriše funkcije. zanima me tudi kam pišem poročila in kako jih povežem v projekt.rmd, da mi jih bo izpisalo

**Comment by jaanos** [comment]
Najprej uredi kodiranje znakov. Datoteko CSV si najbrž izvozil iz Excela, ki uporabi neko nestandardno kodiranje - ker pa posebnih znakov ni preveč, lahko to urediš kar v RStudiu. V datoteki `podatki/LaLiga.csv` poskrbi, da sta pravilno zapisani imeni `Málaga` in `Deportivo La Coruña`, potem pa datoteko shraniš s kodiranjem znakov UTF-8 (v meniju _File_ izberi _Save with Encoding..._). Pri uvozu potem navedi ime datoteke `"podatki/LaLiga.csv"` in parameter `encoding = "UTF-8"`. Ostali dve datoteki z istim imenom pobriši, da ne bosta povzročali zmede.

Graf skušaš prikazati z ukazom `View`, a je ta namenjen le prikazovanju razpredelnic v RStudiu. Če hočeš prikazati graf, enostavno napiši ime spremenljivke, ki ga vsebuje; lahko uporabiš tudi `print`. Sicer pa grafa nočeš prikazovati v programu, pač pa v poročilu.

Poročilo pišeš v datoteki `projekt.Rmd`. V glavi določi naslov in avtorja, potem pa opiši svojo tematiko in uvožene podatke. Vmes so bloki kode - vidiš lahko, da poročilo že kliče program `lib/libraries.r` (tja premakni vse klice `library` in `require`, da ti v poročilo ne bo izpisovalo obvestil ob nalaganju paketov), kasneje pa še `uvoz/uvoz.r`. Tam lahko poklilčeš še `Prikaz.R` (pazi na velikost črk!); na mestu, ki se ti zdi primerno, pa lahko potem še izpišeš graf, ali pa narediš še kakšnega. Vsebino iz vzorca pobriši, da ne bo zaradi tega prihajalo do napak. S klikom na _Knit PDF_ potem prevedeš poročilo v PDF.
